name: chat_app
description: "A WhatsApp Clone Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  
  # UI and utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0  # Required for date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true